[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-core>=0.3.65",
    "langchain[openai]>=0.3.25",
    "langgraph>=0.4.8",
]
